name: ff_commons
description: FlutterFlow Commons Package

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  lullabee:
    path: ../../
  collection: 1.19.1
  equatable: 2.0.5
  http: 1.1.0
  mime_type: 1.0.0

dependency_overrides:
  web: 0.5.1
  http: 1.1.0
  collection: 1.19.1

flutter:
