name: Firebase Production Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Firebase Hosting
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        
    - name: Install dependencies
      run: |
        rm -f pubspec.lock
        flutter pub get
      
    - name: Enable Flutter Web
      run: flutter config --enable-web
      
    - name: Build Web
      run: flutter build web --release --web-renderer html
      
    - name: Check if Firebase Service Account exists
      run: |
        if [ -z "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" ]; then
          echo "Error: FIREBASE_SERVICE_ACCOUNT secret is not set"
          exit 1
        else
          echo "FIREBASE_SERVICE_ACCOUNT secret is set"
        fi
        
    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        projectId: lullabee-mdb94s
        channelId: live
      env:
        FIREBASE_CLI_EXPERIMENTS: webframeworks